[package]
name = "rust"
version = "0.2.0"
authors = ["Nick Alexander <nalexander@mozilla.com>"]
edition = "2021"

[dependencies]
jni = "0.21.1"

[lib]
crate-type = ["staticlib", "dylib"]

[features]
default = ["foo"]
foo = []
bar = []

